# Generated by Django 5.1.6 on 2025-02-09 16:14

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('search_history', models.TextField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('course_getted', models.ManyToManyField(blank=True, related_name='users_getted', to='course.course')),
                ('course_paid', models.ManyToManyField(blank=True, related_name='users_paid', to='course.course')),
                ('lesson_complet', models.ManyToManyField(blank=True, related_name='users_completed_lessons', to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizizzAnswer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.CharField(max_length=255)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('quizizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_quizizz_answers', to='course.quizizz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizizz_answer', to='user_app.user')),
            ],
        ),
    ]
