# Generated by Django 5.1.6 on 2025-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='usage_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
